/**
 * Reference Library Access Helpers
 *
 * Purpose:
 * - Provide typed access to the pre-built reference library stored in
 *   `references/library.json`, so code and agents can easily use
 *   documentation snippets (e.g. how to call specific APIs).
 *
 * Notes:
 * - The library is generated by `npm run build:references`.
 * - This module is intended primarily for tooling, docs, and agent
 *   assistance, not for performance-critical runtime paths.
 */
import libraryJson from '../../../references/library.json';

/** Heading extracted from documentation (e.g. <h2>, <h3>). */
export interface ReferenceHeading {
  level: string;
  text: string;
}

/** Basics shape for Cursor Cloud Agents "List Agents" endpoint. */
export interface CursorCloudAgentsListBasics {
  kind: 'cursor-cloud-agents-list';
  summary: string;
  endpoint: {
    method: string;
    path: string;
    description: string;
    auth: {
      type: 'basic';
      headerExample: string;
      curlExample: string;
    };
    queryParameters: Array<{
      name: string;
      type: string;
      description: string;
    }>;
    responseShape: {
      successExample: {
        agents: string;
        cursor: string;
      };
    };
  };
  usageNotes: string[];
}

/** Single entry in the reference library. */
export interface ReferenceEntry {
  name: string;
  url: string | null;
  title?: string;
  headings?: ReferenceHeading[];
  fetchedAt?: string;
  error?: string;
  // For now we only formalize the Cursor Cloud Agents List basics type.
  basics?: CursorCloudAgentsListBasics | unknown;
}

/** Top-level reference library JSON structure. */
export interface ReferenceLibrary {
  generatedAt: string;
  entries: ReferenceEntry[];
}

export const referenceLibrary = libraryJson as ReferenceLibrary;

/**
 * Get the "List Agents" basics for Cursor Cloud Agents API, if present.
 */
export function getCursorCloudAgentsListBasics(): CursorCloudAgentsListBasics | null {
  const entry = referenceLibrary.entries.find((e) => {
    const basics = e.basics as CursorCloudAgentsListBasics | undefined;
    return basics?.kind === 'cursor-cloud-agents-list';
  });

  if (!entry || !entry.basics) {
    return null;
  }

  return entry.basics as CursorCloudAgentsListBasics;
}
